export const getStyles = ({ loading, hasContent, hasMessage, isMobile }) => ({
  page: {
    minHeight: '100vh',
    background: '#ffffff',
    display: 'flex',
    alignItems: isMobile ? 'flex-start' : 'center',
    justifyContent: 'center',
    padding: isMobile ? '40px 20px' : '64px 24px',
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    boxSizing: 'border-box',
  },
  grid: {
    width: '100%',
    maxWidth: '880px',
    display: 'grid',
    gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', 
    gap: isMobile ? '48px' : '72px',
    alignItems: 'start',
  },
  h1: {
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: isMobile ? '1.5rem' : '1.875rem',
    fontWeight: 500,
    letterSpacing: '-0.02em',
    color: '#111',
    lineHeight: 1.15,
    margin: '0 0 8px',
  },
  subtitle: { fontSize: '13px', color: '#aaa', fontWeight: 300, margin: 0 },
  lbl: {
    display: 'block',
    fontSize: '10px',
    fontWeight: 500,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: '#bbb',
    marginBottom: '6px',
  },
  input: {
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    fontSize: '14px',
    fontWeight: 300,
    color: '#111',
    background: 'transparent',
    border: 'none',
    borderBottom: '1.5px solid #ebebeb',
    padding: '9px 0',
    width: '100%',
    outline: 'none',
    resize: 'none',
    display: 'block',
    boxSizing: 'border-box',
  },
  formFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: '12px',
    borderTop: '1px solid #f0f0f0',
    marginTop: '4px',
  },
  btn: {
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    fontSize: '11px',
    fontWeight: 500,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: '#fff',
    background: loading ? '#ccc' : '#111',
    border: 'none',
    padding: '11px 26px',
    cursor: loading ? 'default' : 'pointer',
  },
  previewLabel: {
    fontSize: '10px',
    fontWeight: 500,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: '#bbb',
    marginBottom: '14px',
    display: 'block',
  },
  emailCard: { 
    border: '1px solid #ebebeb', 
    borderRadius: '4px', 
    overflow: 'hidden',
    width: '100%', 
    boxSizing: 'border-box',
    display: 'block', 
  },
  emailHeader: { background: '#111', padding: '16px 20px' },
  emailTag: {
    fontSize: '10px',
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: '#666',
    marginBottom: '66px',
  },
  emailName: {
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: '1rem',
    color: '#fff',
    fontWeight: 400,
    margin: 0,
  },
  emailAddr: { fontSize: '12px', color: '#666', fontWeight: 300, marginTop: '2px' },
  emailMessage: {
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: 1.7,
    fontStyle: 'normal',
    borderLeft: '2px solid #ebebeb',
    paddingLeft: '14px',
    minHeight: '80px',
    whiteSpace: 'pre-wrap',
    color: hasMessage ? '#555' : '#ccc',
    margin: 0,
  },
  dot: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    background: hasContent ? '#4ade80' : '#e5e5e5',
    transition: 'background 0.3s',
    flexShrink: 0,
  },
});